#+TITLE: blorgit (blog powered by org-mode and git)

* design

Thinking of using [[http://github.com/bmizerany/sinatra/tree/master][sinatra]] for the framework, [[http://github.com/eschulte/active_file/tree/master][active_file]] for object
persistence, and [[http://github.com/eschulte/acts_as_org/tree/master][acts_as_org]] for the org-mode exportation/interaction.

The overriding goal will be simplicity.

* notes
** sinatra
Sinatra is a very nice little mini-framework or DSL for writing simple
single-file web applications.

- [[http://sinatra.rubyforge.org/book.html][sinatra-book]]
- [[http://github.com/sinatra/sinatra/tree/master][git-hub/sinatra]]
- [[http://www.sinatrarb.com/faq.html][sinatra-faq]]

*** specific issues
**** send_data
http://sinatra.lighthouseapp.com/projects/9779/tickets/143-send_data-no-longer-present

**** running under a url prefix
- [[http://blog.tannerburson.com/2009/01/multiple-sinatra-90-applications-in-one.html][multiple-sinatra-90-applications-in-one]]
**** deployment with capistrano and nginx
- [[http://pemberthy.blogspot.com/2009/02/deploying-sinatra-applications-with.html][deploying-sinatra-w-capi-ngin-thin]]

* tasks [3/5]
** TODO setup a global configuration file
   :LOGBOOK:
   - State "TODO"       from ""           [2009-03-30 Mon 18:17]
   :END:
currently config items like =$blogs_dir= are specified separately in
- =run.ru= :: which is used by the server
- =blorgit.rb= :: which is used by =rake=

These should all be read from a single configuration file

** DONE setup dir listing
** DONE setup a global object with title/description etc.
this lives in the root of the blogs directory at =.blorgit.yml=
** TODO users
should be read from a yaml file in the blogs directory (allowing
maintenance through git/VC)

** MAYBE optionally read sidebar/title info from template files

* dict

 LocalWords:  sinatra faq
