#+TITLE: blorgit (blog powered by org-mode and git)

* design

Thinking of using [[http://github.com/bmizerany/sinatra/tree/master][sinatra]] for the framework, [[http://github.com/eschulte/active_file/tree/master][active_file]] for object
persistence, and [[http://github.com/eschulte/acts_as_org/tree/master][acts_as_org]] for the org-mode exportation/interaction.

The overriding goal will be simplicity.

* notes
** sinatra
Sinatra is a very nice little mini-framework or DSL for writing simple
single-file web applications.

- [[http://sinatra.rubyforge.org/book.html][sinatra-book]]
- [[http://github.com/sinatra/sinatra/tree/master][git-hub/sinatra]]
- [[http://www.sinatrarb.com/faq.html][sinatra-faq]]

*** specific issues
**** send_data
http://sinatra.lighthouseapp.com/projects/9779/tickets/143-send_data-no-longer-present

**** running under a url prefix
- [[http://blog.tannerburson.com/2009/01/multiple-sinatra-90-applications-in-one.html][multiple-sinatra-90-applications-in-one]]
**** deployment with capistrano and nginx
- [[http://pemberthy.blogspot.com/2009/02/deploying-sinatra-applications-with.html][deploying-sinatra-w-capi-ngin-thin]]

* tasks [4/7]
** DONE setup dir listing
** DONE setup a global object with title/description etc.
this lives in the root of the blogs directory at =.blorgit.yml=
** TODO directory local blorgit config
   :LOGBOOK:
   - State "TODO"       from ""           [2009-04-09 Thu 13:32]
   :END:
Rather than one global blorgit config file, try searching down through
the directories, so that more precise site-configs can be used.

** TODO save hook (for commits to git)
   :LOGBOOK:
   - State "TODO"       from ""           [2009-04-09 Thu 13:31]
   :END:
add a after-save hook for when a blog is saved.

then use this to implement a simple git commit

** TODO users
should be read from a yaml file in the blogs directory (allowing
maintenance through git/VC)

** MAYBE optionally read sidebar/title info from template files

** MAYBE add support for ruby 1.9
   :LOGBOOK:
   - State "TODO"       from ""           [2009-04-02 Thu 06:22]
   :END:

after a fresh install on debian with ruby1.9, *note* works with ruby1.8

#+begin_example 
(in /home/eschulte/src/blorgit)
rake aborted!
uninitialized constant URI::Parser
/home/eschulte/src/blorgit/Rakefile:1:in `require'
(See full trace by running task with --trace)
#+end_example

* dict

 LocalWords:  sinatra faq
